version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: gin-framework
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  api:
    build: .
    restart: always
    ports:
      - 8888:8000
      - 9999:9000
    depends_on:
      - db
