version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DB: gin-framework
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  api:
    build: .
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - db
